-- 01_schema.sql
-- Create tables for the Dynamic Charts demo

CREATE TABLE regions (
    region_id   NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    region_name VARCHAR2(50) NOT NULL
);

CREATE TABLE orders (
    order_id      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    customer_name VARCHAR2(100),
    order_total   NUMBER,
    order_date    DATE,
    region_id     NUMBER,
    CONSTRAINT fk_orders_region FOREIGN KEY (region_id) REFERENCES regions(region_id)
);

-- Create indexes for performance (as mentioned in the article)
CREATE INDEX idx_orders_date ON orders(order_date);
CREATE INDEX idx_orders_region ON orders(region_id);
