-- DDL for demo_invoices
CREATE TABLE demo_invoices (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_name VARCHAR2(100),
    amount NUMBER,
    status VARCHAR2(20) CHECK (status IN ('DRAFT', 'PENDING', 'APPROVED')),
    due_date DATE
);
