-- =============================================================================
-- APEX Insights | Performance Tuning in Interactive Reports
-- Data Generation Script for Demo Environments (apex.oracle.com / Free Tier)
-- =============================================================================

-- 1. Create the Test Table
-- If the table already exists, this might error. You can drop it first if needed:
-- DROP TABLE IR_PERF_TEST;

CREATE TABLE IR_PERF_TEST (
    id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_number VARCHAR2(50),
    order_date   DATE,
    amount       NUMBER(10,2),
    status       VARCHAR2(20),
    padding      VARCHAR2(100)
);

-- 2. Insert 100,000 Rows (Optimized for Free Tier Quotas)
-- We use 100k instead of 1M to stay within the 25MB limit of apex.oracle.com
INSERT INTO IR_PERF_TEST (order_number, order_date, amount, status, padding)
SELECT 
    'ORD-' || LEVEL,
    SYSDATE - DBMS_RANDOM.VALUE(1, 1000),
    DBMS_RANDOM.VALUE(10, 5000),
    decode(mod(LEVEL, 4), 0, 'OPEN', 1, 'CLOSED', 2, 'PENDING', 'CANCELLED'),
    'Demo data row ' || LEVEL
FROM DUAL
CONNECT BY LEVEL <= 100000;

COMMIT;

-- 3. Create Supporting Index
CREATE INDEX IR_PERF_STATUS_IDX ON IR_PERF_TEST(status);

-- 4. Create the Bottleneck Function (The "Loop" delay)
-- This creates a controllable delay to simulate heavy per-row processing.
CREATE OR REPLACE FUNCTION get_slow_value(p_id IN NUMBER) 
RETURN NUMBER 
IS
    l_sum NUMBER := 0;
BEGIN
    -- This loop creates a measurable delay (approx 0.01s - 0.05s depending on environment)
    FOR i IN 1..100000 LOOP
        l_sum := l_sum + sqrt(i);
    END LOOP;
    RETURN p_id;
END;
/

-- 5. Gather Statistics
BEGIN
    DBMS_STATS.GATHER_TABLE_STATS(
        ownname => sys_context('userenv', 'current_schema'),
        tabname => 'IR_PERF_TEST'
    );
END;
/
